name: Learn Pipeline

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1
      run: echo "Code pushed"

    - name: Step 2
      run: echo "Robot is working"

    - name: Step 3
      run: echo "Pipeline complete"
