name: Build Website

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Get code
      uses: actions/checkout@v3

    - name: Step 2 - Show files
      run: ls

    - name: Step 3 - Create build folder
      run: mkdir build

    - name: Step 4 - Copy website files
      run: cp index.html build/

    - name: Step 5 - Show build folder
      run: ls build
